version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    container_name: keycloak
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=Admin228
    ports:
      - "8180:8080"
    command:
      - start-dev